# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jstanhope3/Dropbox/school_notes/ece4122/4122_Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jstanhope3/Dropbox/school_notes/ece4122/4122_Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jstanhope3/Dropbox/school_notes/ece4122/4122_Project/CMakeFiles /home/jstanhope3/Dropbox/school_notes/ece4122/4122_Project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jstanhope3/Dropbox/school_notes/ece4122/4122_Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named gamelib

# Build rule for target.
gamelib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gamelib
.PHONY : gamelib

# fast build rule for target.
gamelib/fast:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/build
.PHONY : gamelib/fast

Client.o: Client.cpp.o

.PHONY : Client.o

# target to build an object file
Client.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Client.cpp.o
.PHONY : Client.cpp.o

Client.i: Client.cpp.i

.PHONY : Client.i

# target to preprocess a source file
Client.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Client.cpp.i
.PHONY : Client.cpp.i

Client.s: Client.cpp.s

.PHONY : Client.s

# target to generate assembly for a file
Client.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Client.cpp.s
.PHONY : Client.cpp.s

Server.o: Server.cpp.o

.PHONY : Server.o

# target to build an object file
Server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Server.cpp.o
.PHONY : Server.cpp.o

Server.i: Server.cpp.i

.PHONY : Server.i

# target to preprocess a source file
Server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Server.cpp.i
.PHONY : Server.cpp.i

Server.s: Server.cpp.s

.PHONY : Server.s

# target to generate assembly for a file
Server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Server.cpp.s
.PHONY : Server.cpp.s

src/builder/BoardFactory.o: src/builder/BoardFactory.cpp.o

.PHONY : src/builder/BoardFactory.o

# target to build an object file
src/builder/BoardFactory.cpp.o:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/builder/BoardFactory.cpp.o
.PHONY : src/builder/BoardFactory.cpp.o

src/builder/BoardFactory.i: src/builder/BoardFactory.cpp.i

.PHONY : src/builder/BoardFactory.i

# target to preprocess a source file
src/builder/BoardFactory.cpp.i:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/builder/BoardFactory.cpp.i
.PHONY : src/builder/BoardFactory.cpp.i

src/builder/BoardFactory.s: src/builder/BoardFactory.cpp.s

.PHONY : src/builder/BoardFactory.s

# target to generate assembly for a file
src/builder/BoardFactory.cpp.s:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/builder/BoardFactory.cpp.s
.PHONY : src/builder/BoardFactory.cpp.s

src/gamerules/Board.o: src/gamerules/Board.cpp.o

.PHONY : src/gamerules/Board.o

# target to build an object file
src/gamerules/Board.cpp.o:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/gamerules/Board.cpp.o
.PHONY : src/gamerules/Board.cpp.o

src/gamerules/Board.i: src/gamerules/Board.cpp.i

.PHONY : src/gamerules/Board.i

# target to preprocess a source file
src/gamerules/Board.cpp.i:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/gamerules/Board.cpp.i
.PHONY : src/gamerules/Board.cpp.i

src/gamerules/Board.s: src/gamerules/Board.cpp.s

.PHONY : src/gamerules/Board.s

# target to generate assembly for a file
src/gamerules/Board.cpp.s:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/gamerules/Board.cpp.s
.PHONY : src/gamerules/Board.cpp.s

src/gamerules/BoardSpace.o: src/gamerules/BoardSpace.cpp.o

.PHONY : src/gamerules/BoardSpace.o

# target to build an object file
src/gamerules/BoardSpace.cpp.o:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/gamerules/BoardSpace.cpp.o
.PHONY : src/gamerules/BoardSpace.cpp.o

src/gamerules/BoardSpace.i: src/gamerules/BoardSpace.cpp.i

.PHONY : src/gamerules/BoardSpace.i

# target to preprocess a source file
src/gamerules/BoardSpace.cpp.i:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/gamerules/BoardSpace.cpp.i
.PHONY : src/gamerules/BoardSpace.cpp.i

src/gamerules/BoardSpace.s: src/gamerules/BoardSpace.cpp.s

.PHONY : src/gamerules/BoardSpace.s

# target to generate assembly for a file
src/gamerules/BoardSpace.cpp.s:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/gamerules/BoardSpace.cpp.s
.PHONY : src/gamerules/BoardSpace.cpp.s

src/gamerules/Player.o: src/gamerules/Player.cpp.o

.PHONY : src/gamerules/Player.o

# target to build an object file
src/gamerules/Player.cpp.o:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/gamerules/Player.cpp.o
.PHONY : src/gamerules/Player.cpp.o

src/gamerules/Player.i: src/gamerules/Player.cpp.i

.PHONY : src/gamerules/Player.i

# target to preprocess a source file
src/gamerules/Player.cpp.i:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/gamerules/Player.cpp.i
.PHONY : src/gamerules/Player.cpp.i

src/gamerules/Player.s: src/gamerules/Player.cpp.s

.PHONY : src/gamerules/Player.s

# target to generate assembly for a file
src/gamerules/Player.cpp.s:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/gamerules/Player.cpp.s
.PHONY : src/gamerules/Player.cpp.s

src/gamerules/Property.o: src/gamerules/Property.cpp.o

.PHONY : src/gamerules/Property.o

# target to build an object file
src/gamerules/Property.cpp.o:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/gamerules/Property.cpp.o
.PHONY : src/gamerules/Property.cpp.o

src/gamerules/Property.i: src/gamerules/Property.cpp.i

.PHONY : src/gamerules/Property.i

# target to preprocess a source file
src/gamerules/Property.cpp.i:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/gamerules/Property.cpp.i
.PHONY : src/gamerules/Property.cpp.i

src/gamerules/Property.s: src/gamerules/Property.cpp.s

.PHONY : src/gamerules/Property.s

# target to generate assembly for a file
src/gamerules/Property.cpp.s:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/gamerules/Property.cpp.s
.PHONY : src/gamerules/Property.cpp.s

src/multiplayer/MultiplayerObjects.o: src/multiplayer/MultiplayerObjects.cpp.o

.PHONY : src/multiplayer/MultiplayerObjects.o

# target to build an object file
src/multiplayer/MultiplayerObjects.cpp.o:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/multiplayer/MultiplayerObjects.cpp.o
.PHONY : src/multiplayer/MultiplayerObjects.cpp.o

src/multiplayer/MultiplayerObjects.i: src/multiplayer/MultiplayerObjects.cpp.i

.PHONY : src/multiplayer/MultiplayerObjects.i

# target to preprocess a source file
src/multiplayer/MultiplayerObjects.cpp.i:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/multiplayer/MultiplayerObjects.cpp.i
.PHONY : src/multiplayer/MultiplayerObjects.cpp.i

src/multiplayer/MultiplayerObjects.s: src/multiplayer/MultiplayerObjects.cpp.s

.PHONY : src/multiplayer/MultiplayerObjects.s

# target to generate assembly for a file
src/multiplayer/MultiplayerObjects.cpp.s:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/multiplayer/MultiplayerObjects.cpp.s
.PHONY : src/multiplayer/MultiplayerObjects.cpp.s

src/statemachine/StateMachine.o: src/statemachine/StateMachine.cpp.o

.PHONY : src/statemachine/StateMachine.o

# target to build an object file
src/statemachine/StateMachine.cpp.o:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/statemachine/StateMachine.cpp.o
.PHONY : src/statemachine/StateMachine.cpp.o

src/statemachine/StateMachine.i: src/statemachine/StateMachine.cpp.i

.PHONY : src/statemachine/StateMachine.i

# target to preprocess a source file
src/statemachine/StateMachine.cpp.i:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/statemachine/StateMachine.cpp.i
.PHONY : src/statemachine/StateMachine.cpp.i

src/statemachine/StateMachine.s: src/statemachine/StateMachine.cpp.s

.PHONY : src/statemachine/StateMachine.s

# target to generate assembly for a file
src/statemachine/StateMachine.cpp.s:
	$(MAKE) -f CMakeFiles/gamelib.dir/build.make CMakeFiles/gamelib.dir/src/statemachine/StateMachine.cpp.s
.PHONY : src/statemachine/StateMachine.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... client"
	@echo "... server"
	@echo "... edit_cache"
	@echo "... gamelib"
	@echo "... Client.o"
	@echo "... Client.i"
	@echo "... Client.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... src/builder/BoardFactory.o"
	@echo "... src/builder/BoardFactory.i"
	@echo "... src/builder/BoardFactory.s"
	@echo "... src/gamerules/Board.o"
	@echo "... src/gamerules/Board.i"
	@echo "... src/gamerules/Board.s"
	@echo "... src/gamerules/BoardSpace.o"
	@echo "... src/gamerules/BoardSpace.i"
	@echo "... src/gamerules/BoardSpace.s"
	@echo "... src/gamerules/Player.o"
	@echo "... src/gamerules/Player.i"
	@echo "... src/gamerules/Player.s"
	@echo "... src/gamerules/Property.o"
	@echo "... src/gamerules/Property.i"
	@echo "... src/gamerules/Property.s"
	@echo "... src/multiplayer/MultiplayerObjects.o"
	@echo "... src/multiplayer/MultiplayerObjects.i"
	@echo "... src/multiplayer/MultiplayerObjects.s"
	@echo "... src/statemachine/StateMachine.o"
	@echo "... src/statemachine/StateMachine.i"
	@echo "... src/statemachine/StateMachine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

